// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChQ4gdW7F0PVJHyacgWVuw21YUY-I9spM',
    appId: '1:468386151754:web:ff0b95a54ec3c30632d5b3',
    messagingSenderId: '468386151754',
    projectId: 'peta-bencana-3edd2',
    authDomain: 'peta-bencana-3edd2.firebaseapp.com',
    storageBucket: 'peta-bencana-3edd2.firebasestorage.app',
    measurementId: 'G-H0ZGEVVZST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp3nJbHhm5nIYWPj7sf_tMd_aWUdwcthU',
    appId: '1:468386151754:android:81240a9908afb86f32d5b3',
    messagingSenderId: '468386151754',
    projectId: 'peta-bencana-3edd2',
    storageBucket: 'peta-bencana-3edd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1RrZ5xLJJSQrqc3KdOMw2WsHqD-rFemo',
    appId: '1:468386151754:ios:bf379ccd45c8f10f32d5b3',
    messagingSenderId: '468386151754',
    projectId: 'peta-bencana-3edd2',
    storageBucket: 'peta-bencana-3edd2.firebasestorage.app',
    iosBundleId: 'com.example.tasikSiaga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1RrZ5xLJJSQrqc3KdOMw2WsHqD-rFemo',
    appId: '1:468386151754:ios:bf379ccd45c8f10f32d5b3',
    messagingSenderId: '468386151754',
    projectId: 'peta-bencana-3edd2',
    storageBucket: 'peta-bencana-3edd2.firebasestorage.app',
    iosBundleId: 'com.example.tasikSiaga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChQ4gdW7F0PVJHyacgWVuw21YUY-I9spM',
    appId: '1:468386151754:web:475f1467dd85970e32d5b3',
    messagingSenderId: '468386151754',
    projectId: 'peta-bencana-3edd2',
    authDomain: 'peta-bencana-3edd2.firebaseapp.com',
    storageBucket: 'peta-bencana-3edd2.firebasestorage.app',
    measurementId: 'G-C7TRQYLNF4',
  );
}
